/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.ccektortest

import io.ktor.server.application.*
import io.ktor.util.*

class MyCalculatorPlugin {
    class Configuration
    companion object Plugin : BaseApplicationPlugin<ApplicationCallPipeline, Configuration, MyCalculatorPlugin> {
        override val key = AttributeKey<MyCalculatorPlugin>("MyCalculatorPlugin")

        override fun install(
            pipeline: ApplicationCallPipeline,
            configure: Configuration.() -> Unit
        ): MyCalculatorPlugin {
            return MyCalculatorPlugin()
        }

    }

    fun add(x: Int, y: Int): Int {
        return x + y
    }
}

val Application.myCalculator get() = plugin(MyCalculatorPlugin)
