/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.example.ccektortest

import io.ktor.server.application.*
import io.ktor.server.testing.*
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class LibraryTest {
    @Test
    fun `Test simple sum via 'myCalculator' utility property`() = testApplication {
        install(MyCalculatorPlugin)
        application {
            val result = myCalculator.add(1, 2)
            assertEquals(3, result)
        }
    }

    @Test
    fun `Test simple sum via 'plugin' function`() = testApplication {
        install(MyCalculatorPlugin)
        application {
            val result = plugin(MyCalculatorPlugin).add(1, 2)
            assertEquals(3, result)
        }
    }
}
