name: CI

on:
  push:
    branches: [main]

jobs:
  validate-wrapper:
    name: "Validate Gradle wrapper"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1

  check:
    name: "Run tests & checks"
    runs-on: ubuntu-latest
    needs: [validate-wrapper]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run checks and tests
        run: ./gradlew check
